### PR TITLE
Craigified addressing half of #1

### PR DESCRIPTION
**Pull request by ColinHarrington**
Adding quercus for PHP support: addressing half of Issue #1

### CODE REVIEW

**Comment by danveloper** [comment]
dear god.

**Comment by danveloper** [comment]
might as well change those spaces to tabs

**Comment by ColinHarrington** [comment]
Ha, Fixed. That's what I get for cranking it out in with an unconfigured editor :-)

**Comment by davydotcom** [comment]
why the hell hasn't this been merged yet?

**Comment by danveloper** [comment]
well the project is `Gradle + Kotlin + JavaScript + Kotlin + JavaScript`... see PHP in there anywhere?

Also, this monstrosity may be worthy of its own project.

**Comment by ColinHarrington** [comment]
> well the project is `Gradle + Kotlin + JavaScript + Kotlin + JavaScript`... see PHP in there anywhere?

You're right, It's clearly out of scope. 

> Also, this monstrosity may be worthy of its own project.

Yes, but No, That's not on my list of things that deserve life and opensource attention, I'm piping this one to `/dev/null`

(👋  hope all is well @danveloper @craigburke @davydotcom)

**Pull request closed without merging**
